name: Build and publish Docker distributions to ghcr.io and Java distributions to sonatype

on:
  push:
    branches:
      - master
      - version-*
    paths:
      - gradle.properties

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      build-target: 'Sonatype,Docker'
      docker-username: ${{ github.actor }}
      runsOn: ubuntu-latest
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
      docker-password: ${{ secrets.GITHUB_TOKEN }}
